import { access, readFile, readdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const appRoot=resolve(dirname(fileURLToPath(import.meta.url)),'..');const repoRoot=resolve(appRoot,'../..');
const read=p=>readFile(resolve(appRoot,p),'utf8'),readRoot=p=>readFile(resolve(repoRoot,p),'utf8');
const required=['src/server.mjs','src/lib/apiFootball.mjs','src/lib/statsApi.mjs','src/lib/venueStats.mjs','src/engines/marketRoute.mjs','src/engines/ppgRoute.mjs','src/engines/apexIntelligence.mjs','src/engines/convergence.mjs','src/engines/momentumStreak.mjs','src/engines/streakValue.mjs','src/engines/htftMomentum.mjs','src/engines/zeusIntelligence.mjs','src/engines/universalOddsGate.mjs','src/engines/consensus.mjs','public/index.html','public/app.js','public/styles.css','public/sw.js','public/zeus.html','public/zeus.js','public/streak-value.html','public/streak-value.js','public/htft-momentum.html','public/htft-momentum.js','sql/016_zeus_statistical_supervisor.sql','package.json','package-lock.json','.env.example'];
for(const p of required)await access(resolve(appRoot,p));for(const p of ['render.yaml','package.json','scripts/verify-single-render.mjs','RELEASE_V5_0_18.md'])await access(resolve(repoRoot,p));
const [server,stats,api,sw,styles,env,render,rootPkgText,pkgText,lockText,index,picks,app,zeus]=await Promise.all([read('src/server.mjs'),read('src/lib/statsApi.mjs'),read('src/lib/apiFootball.mjs'),read('public/sw.js'),read('public/styles.css'),read('.env.example'),readRoot('render.yaml'),readRoot('package.json'),read('package.json'),read('package-lock.json'),read('public/index.html'),read('public/picks.html'),read('public/app.js'),read('src/engines/zeusIntelligence.mjs')]);
if(!/const APP_VERSION = '5\.0\.18'/.test(server))throw new Error('Server version is not 5.0.18.');
for(const code of ['MARKET_ROUTE','PPG_ROUTE','APEX_INTELLIGENCE','CONVERGENCE_ROUTE','MOMENTUM_STREAK','STREAK_VALUE','HTFT_MOMENTUM','ZEUS_SUPERVISOR'])if(!server.includes(code))throw new Error(`Missing engine/supervisor ${code}.`);
for(const token of ['analyzeStreakValue','analyzeHtftMomentum','analyzeZeusIntelligence','applyZeusSupervisor','buildStatsApiFixtureEvidence','statsApiRateState'])if(!server.includes(token))throw new Error(`Missing intelligence wiring ${token}.`);
for(const route of ['streak-value-board','htft-momentum-board','zeus-board','ppg-route-board','apex-intelligence-board','convergence-route-board','momentum-streak-board'])if(!server.includes(route))throw new Error(`Missing route ${route}.`);
for(const label of ['Atlas Streak','Chronos HT/FT','Zeus','SEVEN ENGINES','ZEUS SUPERVISION'])if(!index.includes(label))throw new Error(`Dashboard missing ${label}.`);
if(!/7\/7/.test(index)||!/5–6\/7|5-6\/7/.test(index))throw new Error('Seven-engine consensus labels missing.');
if(!/renderStreakValueEngine/.test(app)||!/renderHtftEngine/.test(app)||!/renderZeusEngine/.test(app))throw new Error('Match intelligence rendering incomplete.');
if(!/betynz-v5-0-18/.test(sw)||!/streak-value\.html/.test(sw)||!/htft-momentum\.html/.test(sw)||!/zeus\.html/.test(sw))throw new Error('PWA shell not upgraded for Zeus.');
if(!/zeus-page/.test(styles)||!/betynzEnginePulse/.test(styles))throw new Error('Zeus palette/light motion CSS missing.');
for(const key of ['STATS_API_KEY','STATS_API_BASE_URL','STATS_API_REQUESTS_PER_MINUTE','STATS_VALUE_CONCURRENCY'])if(!env.includes(key)||!render.includes(key))throw new Error(`Stats API configuration missing ${key}.`);
if(!/api\.thestatsapi\.com/.test(stats)||!/Authorization: `Bearer/.test(stats)||!/teamOver15/.test(stats)||!/xgFor/.test(stats)||!/sotFor/.test(stats))throw new Error('Stats API streak/xG/SOT contract incomplete.');
if(!/htftHomeHome/.test(api))throw new Error('API-Football HT/FT odds normalization missing.');
if(!/seven independent engines/i.test(picks)||!/Zeus/i.test(picks))throw new Error('Picks page not upgraded for Zeus supervision.');
if((render.match(/^\s*-\s+type:\s+web\s*$/gm)||[]).length!==1)throw new Error('Render must define one web service.');
if(!/API_FOOTBALL_MEDIA_CACHE_MAX_MB/.test(render)||!/ANALYSIS_SNAPSHOT_MAX_DATES/.test(render)||!/runtimeMemory/.test(server))throw new Error('Runtime 502 stability controls are missing.');
if(!/dataQuality/.test(zeus)||!/MATCHUP:18/.test(zeus)||!/applyZeusSupervisor/.test(zeus)||!/ZEUS_HOLD/.test(zeus))throw new Error('Zeus supervisor contract incomplete.');
const pkg=JSON.parse(pkgText),lock=JSON.parse(lockText),rootPkg=JSON.parse(rootPkgText);if(pkg.version!=='5.0.18'||lock.version!=='5.0.18'||rootPkg.version!=='5.0.18')throw new Error('Package versions are not 5.0.18.');
const tests=(await readdir(resolve(appRoot,'test'))).sort();
const gate=await read('src/engines/universalOddsGate.mjs');if(!/MIN_ODDS = 1\.20/.test(gate)||!/MAX_ODDS = 2\.00/.test(gate))throw new Error('Universal 1.20–2.00 odds gate is missing.');
for(const name of ['universal-odds-gate.test.mjs','streak-value.test.mjs','htft-momentum.test.mjs','transient-502-resilience.test.mjs','eight-engine-zeus.test.mjs','zeus-intelligence.test.mjs','runtime-stability.test.mjs'])if(!tests.includes(name))throw new Error(`Missing test ${name}.`);
console.log(`Release verification passed: Betynz 5.0.18 seven-engine system with Zeus statistical supervision, runtime stability and universal odds gate; ${tests.length} test files.`);
