import { access, readFile, readdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const appRoot=resolve(dirname(fileURLToPath(import.meta.url)),'..');const repoRoot=resolve(appRoot,'../..');
const read=p=>readFile(resolve(appRoot,p),'utf8'),readRoot=p=>readFile(resolve(repoRoot,p),'utf8');
const required=['src/server.mjs','src/lib/apiFootball.mjs','src/lib/statsApi.mjs','src/lib/venueStats.mjs','src/engines/marketRoute.mjs','src/engines/ppgRoute.mjs','src/engines/apexIntelligence.mjs','src/engines/convergence.mjs','src/engines/momentumStreak.mjs','src/engines/streakValue.mjs','src/engines/htftMomentum.mjs','src/engines/consensus.mjs','public/index.html','public/app.js','public/styles.css','public/sw.js','public/streak-value.html','public/streak-value.js','public/htft-momentum.html','public/htft-momentum.js','sql/015_seven_engine_stats_htft.sql','package.json','package-lock.json','.env.example'];
for(const p of required)await access(resolve(appRoot,p));for(const p of ['render.yaml','package.json','scripts/verify-single-render.mjs','RELEASE_V5_0_14.md'])await access(resolve(repoRoot,p));
const [server,stats,api,sw,styles,env,render,rootPkgText,pkgText,lockText,index,picks,app]=await Promise.all([read('src/server.mjs'),read('src/lib/statsApi.mjs'),read('src/lib/apiFootball.mjs'),read('public/sw.js'),read('public/styles.css'),read('.env.example'),readRoot('render.yaml'),readRoot('package.json'),read('package.json'),read('package-lock.json'),read('public/index.html'),read('public/picks.html'),read('public/app.js')]);
if(!/const APP_VERSION = '5\.0\.14'/.test(server))throw new Error('Server version is not 5.0.14.');
for(const code of ['MARKET_ROUTE','PPG_ROUTE','APEX_INTELLIGENCE','CONVERGENCE_ROUTE','MOMENTUM_STREAK','STREAK_VALUE','HTFT_MOMENTUM'])if(!server.includes(code))throw new Error(`Missing engine ${code}.`);
for(const token of ['analyzeStreakValue','analyzeHtftMomentum','buildStatsApiFixtureEvidence','statsApiRateState'])if(!server.includes(token))throw new Error(`Missing seven-engine wiring ${token}.`);
for(const route of ['streak-value-board','htft-momentum-board','ppg-route-board','apex-intelligence-board','convergence-route-board','momentum-streak-board'])if(!server.includes(route))throw new Error(`Missing route ${route}.`);
for(const label of ['Atlas Streak','Chronos HT/FT','SEVEN ENGINES'])if(!index.includes(label))throw new Error(`Dashboard missing ${label}.`);
if(!/7\/7/.test(index)||!/5–6\/7|5-6\/7/.test(index))throw new Error('Seven-engine consensus labels missing.');
if(!/renderStreakValueEngine/.test(app)||!/renderHtftEngine/.test(app)||!/\/ 7 \* 100/.test(app))throw new Error('Seven-engine match intelligence rendering missing.');
if(!/betynz-v5-0-14/.test(sw)||!/streak-value\.html/.test(sw)||!/htft-momentum\.html/.test(sw))throw new Error('PWA shell not upgraded.');
if(!/repeat\(7/.test(styles)||!/betynzEnginePulse/.test(styles))throw new Error('Seven-engine palette/light motion CSS missing.');
for(const key of ['STATS_API_KEY','STATS_API_BASE_URL','STATS_API_REQUESTS_PER_MINUTE','STATS_VALUE_CONCURRENCY'])if(!env.includes(key)||!render.includes(key))throw new Error(`Stats API configuration missing ${key}.`);
if(!/api\.thestatsapi\.com/.test(stats)||!/Authorization: `Bearer/.test(stats)||!/teamOver15/.test(stats)||!/xgFor/.test(stats)||!/sotFor/.test(stats))throw new Error('Stats API streak/xG/SOT contract incomplete.');
if(!/htftHomeHome/.test(api))throw new Error('API-Football HT/FT odds normalization missing.');
if(!/seven independent engines/i.test(picks))throw new Error('Picks page not upgraded to seven engines.');
if((render.match(/^\s*-\s+type:\s+web\s*$/gm)||[]).length!==1)throw new Error('Render must define one web service.');
const pkg=JSON.parse(pkgText),lock=JSON.parse(lockText),rootPkg=JSON.parse(rootPkgText);if(pkg.version!=='5.0.14'||lock.version!=='5.0.14'||rootPkg.version!=='5.0.14')throw new Error('Package versions are not 5.0.14.');
const tests=(await readdir(resolve(appRoot,'test'))).sort();for(const name of ['streak-value.test.mjs','htft-momentum.test.mjs','transient-502-resilience.test.mjs','seven-engine-reset.test.mjs'])if(!tests.includes(name))throw new Error(`Missing test ${name}.`);
console.log(`Release verification passed: Betynz 5.0.14 seven-engine Stats/HTFT edition with ${tests.length} test files.`);
