import { round } from '../lib/utils.mjs';

const n=v=>Number.isFinite(Number(v))?Number(v):null;
const offered=v=>n(v)!==null&&n(v)>1;
const fmt=v=>offered(v)?n(v).toFixed(2):'—';
function form(value){return(Array.isArray(value)?value:String(value||'').toUpperCase().match(/[WDL]/g)||[]).map(String).map(x=>x.toUpperCase()).filter(x=>['W','D','L'].includes(x)).slice(0,5);}
function streak(arr,fn){let c=0;for(const x of arr||[]){if(!fn(x))break;c++;}return c;}
function norm(split){if(!split)return null;const f=form(split.form);return{...split,played:Number(split.played||f.length||0),form:f,wins:Number(split.wins||f.filter(x=>x==='W').length),losses:Number(split.losses||f.filter(x=>x==='L').length),ppg:n(split.ppg),firstHalfOver05:Number(split.firstHalfOver05||0),firstHalfGoalsAvg:n(split.firstHalfGoalsAvg)||0,halfTimeAvailable:Number(split.halfTimeAvailable||0),htft:{WW:0,DW:0,LW:0,WD:0,DD:0,LD:0,WL:0,DL:0,LL:0,...(split.htft||{})}};}
function c(label,pass,actual,rule,family,weight=1){return{label,pass:Boolean(pass),actual,rule,family,weight};}
function make({id,name,direction,target,safer,checks,blockers=[]}){const ok=checks.filter(x=>x.pass),families=new Set(ok.map(x=>x.family));const weight=checks.reduce((s,x)=>s+x.weight,0),got=ok.reduce((s,x)=>s+x.weight,0),score=round(got/Math.max(1,weight)*100,1);const blocks=blockers.filter(Boolean);let selection=null;if(!blocks.length&&families.size>=3&&score>=82&&offered(target?.odds))selection={...target,decision:'FIRE'};else if(!blocks.length&&families.size>=3&&score>=72&&offered(safer?.odds))selection={...safer,decision:'SAFER',downgradedFrom:target?.market||null};const reasons=[...ok.slice(0,6).map(x=>`${x.label}: ${x.actual}.`),...checks.filter(x=>!x.pass).slice(0,3).map(x=>`${x.label} missed: ${x.actual}; need ${x.rule}.`),...blocks.map(x=>`Blocked: ${x}`)];if(selection)Object.assign(selection,{routeId:id,routeName:name,score,grade:score>=92?'A+':score>=86?'A':selection.decision==='FIRE'?'B+':'SAFER',reasons,evidenceFamilies:[...families]});return{id,name,direction,target,safer,checks,blockers:blocks,score,selection,reasons};}
function pickBest(candidates){const q=candidates.filter(x=>x.selection);const home=q.filter(x=>x.direction==='HOME_RESULT').sort((a,b)=>b.score-a.score)[0],away=q.filter(x=>x.direction==='AWAY_RESULT').sort((a,b)=>b.score-a.score)[0];if(home&&away&&Math.abs(home.score-away.score)<=8)return{conflict:true,reason:'Home and away HT/FT routes are almost equally strong.'};return{conflict:false,best:q.sort((a,b)=>b.score-a.score||Number(a.selection?.odds||99)-Number(b.selection?.odds||99))[0]||null};}

export function analyzeHtftMomentum(fixture={},stats=null){
 const odds=fixture.odds||{},home=norm(stats?.homeSplit||stats?.home),away=norm(stats?.awaySplit||stats?.away);const base={engine:'HTFT_MOMENTUM',decision:'NO_SIGNAL',selection:null,candidates:[],home,away,explanation:'No HT/FT transition route qualified.'};
 if(!home||!away||home.played<5||away.played<5)return{...base,decision:'WAITING',explanation:`Five home and five away matches are required. Home ${home?.played||0}/5; away ${away?.played||0}/5.`};
 if(home.halfTimeAvailable<3||away.halfTimeAvailable<3)return{...base,decision:'WAITING',explanation:`HT/FT data is too thin. Home ${home.halfTimeAvailable}; away ${away.halfTimeAvailable} usable half-time samples.`};
 const hs={wins:streak(home.form,x=>x==='W'),unbeaten:streak(home.form,x=>x!=='L'),losses:streak(home.form,x=>x==='L'),winless:streak(home.form,x=>x!=='W')};
 const as={wins:streak(away.form,x=>x==='W'),unbeaten:streak(away.form,x=>x!=='L'),losses:streak(away.form,x=>x==='L'),winless:streak(away.form,x=>x!=='W')};
 const C=[];
 C.push(make({id:'HTFT_HOME_HOLD',name:'Home lead-and-hold transition',direction:'HOME_RESULT',target:{market:'HTFT_HOME_HOME',label:'Half Time / Full Time — Home / Home',odds:n(odds.htftHomeHome)},safer:{market:'HOME_WIN',label:'Home Team to Win',odds:n(odds.homeWin)},checks:[c('Home WW transitions',home.htft.WW>=2,`${home.htft.WW}/${home.halfTimeAvailable}`,'≥ 2','TRANSITION',3),c('Away LL transitions',away.htft.LL>=2,`${away.htft.LL}/${away.halfTimeAvailable}`,'≥ 2','OPPOSITION_TRANSITION',3),c('Home momentum',hs.unbeaten>=4||home.wins>=4,`${hs.unbeaten} unbeaten · ${home.wins}/5 wins`,'4 unbeaten or 4 wins','MOMENTUM',2),c('Away weakness',as.winless>=3||away.losses>=3,`${as.winless} winless · ${away.losses}/5 losses`,'3 winless or 3 losses','OPPOSITION',2),c('HT/FT or safer price',offered(odds.htftHomeHome)||offered(odds.homeWin),`${fmt(odds.htftHomeHome)} / ${fmt(odds.homeWin)}`,'market available','MARKET',2)],blockers:[home.htft.WL+home.htft.WD>=2?'Home often loses or surrenders half-time leads.':null]}));
 C.push(make({id:'HTFT_AWAY_HOLD',name:'Away lead-and-hold transition',direction:'AWAY_RESULT',target:{market:'HTFT_AWAY_AWAY',label:'Half Time / Full Time — Away / Away',odds:n(odds.htftAwayAway)},safer:{market:'AWAY_WIN',label:'Away Team to Win',odds:n(odds.awayWin)},checks:[c('Away WW transitions',away.htft.WW>=2,`${away.htft.WW}/${away.halfTimeAvailable}`,'≥ 2','TRANSITION',3),c('Home LL transitions',home.htft.LL>=2,`${home.htft.LL}/${home.halfTimeAvailable}`,'≥ 2','OPPOSITION_TRANSITION',3),c('Away momentum',as.unbeaten>=4||away.wins>=4,`${as.unbeaten} unbeaten · ${away.wins}/5 wins`,'4 unbeaten or 4 wins','MOMENTUM',2),c('Home weakness',hs.winless>=3||home.losses>=3,`${hs.winless} winless · ${home.losses}/5 losses`,'3 winless or 3 losses','OPPOSITION',2),c('HT/FT or safer price',offered(odds.htftAwayAway)||offered(odds.awayWin),`${fmt(odds.htftAwayAway)} / ${fmt(odds.awayWin)}`,'market available','MARKET',2)],blockers:[away.htft.WL+away.htft.WD>=2?'Away often loses or surrenders half-time leads.':null]}));
 C.push(make({id:'HTFT_DRAW_HOME',name:'Level at half, home acceleration',direction:'HOME_RESULT',target:{market:'HTFT_DRAW_HOME',label:'Half Time / Full Time — Draw / Home',odds:n(odds.htftDrawHome)},safer:{market:'DOUBLE_CHANCE_1X',label:'Home or Draw (1X)',odds:n(odds.doubleChance1X)},checks:[c('Home DW transitions',home.htft.DW>=2,`${home.htft.DW}`,'≥ 2','TRANSITION',3),c('Away DL transitions',away.htft.DL>=1||away.htft.DD>=2,`${away.htft.DL} DL · ${away.htft.DD} DD`,'DL ≥1 or DD ≥2','OPPOSITION_TRANSITION',2),c('Home late strength',home.ppg!==null&&home.ppg>=1.8,`${home.ppg?.toFixed(2)} PPG`,'≥ 1.80','MOMENTUM',2),c('Price available',offered(odds.htftDrawHome)||offered(odds.doubleChance1X),`${fmt(odds.htftDrawHome)} / ${fmt(odds.doubleChance1X)}`,'available','MARKET',2)]}));
 C.push(make({id:'HTFT_DRAW_AWAY',name:'Level at half, away acceleration',direction:'AWAY_RESULT',target:{market:'HTFT_DRAW_AWAY',label:'Half Time / Full Time — Draw / Away',odds:n(odds.htftDrawAway)},safer:{market:'DOUBLE_CHANCE_X2',label:'Draw or Away (X2)',odds:n(odds.doubleChanceX2)},checks:[c('Away DW transitions',away.htft.DW>=2,`${away.htft.DW}`,'≥ 2','TRANSITION',3),c('Home DL transitions',home.htft.DL>=1||home.htft.DD>=2,`${home.htft.DL} DL · ${home.htft.DD} DD`,'DL ≥1 or DD ≥2','OPPOSITION_TRANSITION',2),c('Away late strength',away.ppg!==null&&away.ppg>=1.8,`${away.ppg?.toFixed(2)} PPG`,'≥ 1.80','MOMENTUM',2),c('Price available',offered(odds.htftDrawAway)||offered(odds.doubleChanceX2),`${fmt(odds.htftDrawAway)} / ${fmt(odds.doubleChanceX2)}`,'available','MARKET',2)]}));
 const volatility=(home.htft.LW+home.htft.WL+home.htft.WD)+(away.htft.LW+away.htft.WL+away.htft.WD);
 C.push(make({id:'HTFT_COMEBACK_GOALS',name:'Comeback and swing-goal route',direction:'GOALS_OVER',target:{market:'OVER_2_5',label:'Over 2.5 Goals',odds:n(odds.over25)},safer:{market:'OVER_1_5',label:'Over 1.5 Goals',odds:n(odds.over15)},checks:[c('Swing transitions',volatility>=3,`${volatility} swing transitions`,'≥ 3','TRANSITION',3),c('First-half goal activity',home.firstHalfOver05+away.firstHalfOver05>=6,`${home.firstHalfOver05+away.firstHalfOver05}/10`,'≥ 6/10','FIRST_HALF',2),c('Momentum changes',home.htft.LW+away.htft.LW>=1||home.htft.WL+away.htft.WL>=2,`${home.htft.LW+away.htft.LW} comeback wins`,'≥1 comeback or 2 lost leads','MOMENTUM',2),c('Goal market available',offered(odds.over25)||offered(odds.over15),`${fmt(odds.over25)} / ${fmt(odds.over15)}`,'available','MARKET',2)]}));
 C.push(make({id:'HTFT_EARLY_GOAL',name:'Early-event transition route',direction:'GOALS_OVER',target:{market:'FIRST_HALF_OVER_0_5',label:'First Half Over 0.5 Goals',odds:n(odds.firstHalfOver05)},safer:{market:'OVER_1_5',label:'Over 1.5 Goals',odds:n(odds.over15)},checks:[c('Home first-half goal rate',home.firstHalfOver05>=4,`${home.firstHalfOver05}/5`,'≥4/5','FIRST_HALF',2),c('Away first-half goal rate',away.firstHalfOver05>=4,`${away.firstHalfOver05}/5`,'≥4/5','FIRST_HALF_OPPOSITION',2),c('Decisive HT/FT transitions',home.htft.WW+home.htft.LL+away.htft.WW+away.htft.LL>=4,`${home.htft.WW+home.htft.LL+away.htft.WW+away.htft.LL}`,'≥4','TRANSITION',2),c('Market available',offered(odds.firstHalfOver05)||offered(odds.over15),`${fmt(odds.firstHalfOver05)} / ${fmt(odds.over15)}`,'available','MARKET',2)]}));
 const picked=pickBest(C);if(picked.conflict)return{...base,candidates:C,decision:'CONFLICT',explanation:picked.reason};if(!picked.best)return{...base,candidates:C};return{...base,candidates:C,decision:picked.best.selection.decision,selection:picked.best.selection,explanation:`${picked.best.name}. The engine begins with HT/FT transition frequencies, then requires current momentum/streak support and an offered market.`};
}

export function htftMomentumSummary(rows=[]){return{fixtures:rows.length,fire:rows.filter(x=>x.engine?.decision==='FIRE').length,safer:rows.filter(x=>x.engine?.decision==='SAFER').length,waiting:rows.filter(x=>x.engine?.decision==='WAITING').length,conflict:rows.filter(x=>x.engine?.decision==='CONFLICT').length};}
