import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {calculateSplitStats,analyseMatch,analyseBoard}=require('./goldenBanker.cjs');

const stats=calculateSplitStats([{gf:2,ga:0},{gf:1,ga:0},{gf:3,ga:1},{gf:2,ga:1},{gf:1,ga:0}]);
assert.equal(stats.ppg,3);
assert.equal(stats.avgGA,.4);

const dnb=analyseMatch({league:'T',homeTeam:'H',awayTeam:'A',homeLast5:[{gf:2,ga:0},{gf:1,ga:0},{gf:1,ga:1},{gf:2,ga:1},{gf:0,ga:0}],awayLast5:[{gf:0,ga:2},{gf:0,ga:1},{gf:1,ga:1},{gf:0,ga:3},{gf:0,ga:2}]});
assert.equal(dnb.markets.winDnb.dnbEligible,true);
assert.equal(dnb.markets.winDnb.straightWinEligible,false);

const board=analyseBoard(new Array(6).fill(0).map((_,i)=>({id:`m${i}`,league:'T',homeTeam:`H${i}`,awayTeam:`A${i}`,homeLast5:[{gf:3,ga:0},{gf:2,ga:0},{gf:3,ga:1},{gf:2,ga:1},{gf:3,ga:0}],awayLast5:[{gf:0,ga:3},{gf:0,ga:2},{gf:1,ga:4},{gf:0,ga:3},{gf:1,ga:4}]})));
assert.ok(board.topBankers.length<=4);

const html=readFileSync(new URL('./public/index.html',import.meta.url),'utf8');
const js=readFileSync(new URL('./public/app.js',import.meta.url),'utf8');
const css=readFileSync(new URL('./public/styles.css',import.meta.url),'utf8');
const compact=readFileSync(new URL('./public/compact-board.css',import.meta.url),'utf8');
const splashCss=readFileSync(new URL('./public/splash.css',import.meta.url),'utf8');
const splashJs=readFileSync(new URL('./public/splash.js',import.meta.url),'utf8');
const ratedHtml=readFileSync(new URL('./public/highly-rated.html',import.meta.url),'utf8');
const ratedJs=readFileSync(new URL('./public/highly-rated.js',import.meta.url),'utf8');
const ratedCss=readFileSync(new URL('./public/highly-rated.css',import.meta.url),'utf8');
const ratedLink=readFileSync(new URL('./public/rated-link.js',import.meta.url),'utf8');
const runtimeConfig=readFileSync(new URL('./runtimeConfig.mjs',import.meta.url),'utf8');
const serverSource=readFileSync(new URL('./server.mjs',import.meta.url),'utf8');
const splashAsset=new URL('../web/public/assets/zeus-board-loading.jpg',import.meta.url);
const videoModules=[1,2,3,4,5].map(i=>readFileSync(new URL(`./public/video/zeus-thunder.part0${i}.js`,import.meta.url),'utf8'));
const videoBase64=videoModules.map(source=>{
  const match=source.match(/^export default '([^']+)'/);
  assert.ok(match,`Zeus video chunk must be a base64 module`);
  return match[1];
}).join('');
const videoBuffer=Buffer.from(videoBase64,'base64');

assert.match(html,/data-scope="CANDIDATES"/);
assert.match(html,/id="matchCentreToggle"/);
assert.match(html,/id="centreBody" hidden/);
assert.match(html,/id="pagination"/);
assert.match(html,/id="market"/);
assert.match(html,/id="confidence"/);
assert.match(html,/id="league"/);
assert.match(html,/id="moreHighlyRated"/);
assert.match(html,/highly-rated\.html/);
assert.match(html,/id="boardSplash"/);
assert.match(html,/class="splash-active"/);
assert.match(html,/id="boardSplashVideo"/);
assert.match(html,/src="\/media\/zeus-thunder\.mp4"/);
assert.match(html,/autoplay muted playsinline/);
assert.doesNotMatch(html,/autoplay muted loop playsinline/);
assert.match(html,/poster="\/assets\/zeus-board-loading\.jpg"/);
assert.match(html,/Loading Board…/);
assert.match(html,/LET THE GODS DECIDE/);
assert.match(js,/pageSize:\s*20/);
assert.match(js,/CANDIDATE/);
assert.match(js,/finalBankerIds/);
assert.match(js,/WAITING FOR 5\+5/);
assert.match(js,/Why this pick/);
assert.match(js,/exact home results/);
assert.match(js,/exact away results/);
assert.match(compact,/\.status-badge\.candidate/);
assert.match(compact,/@media\(max-width:540px\)/);
assert.match(css,/@media\(max-width:620px\)/);
assert.match(splashCss,/\.board-splash__video/);
assert.match(splashCss,/object-fit:contain/);
assert.match(splashCss,/transform:none/);
assert.doesNotMatch(splashCss,/zeus-breathe/);
assert.match(splashCss,/board-load/);
assert.match(splashCss,/prefers-reduced-motion/);
assert.doesNotMatch(splashJs,/atob\(/);
assert.doesNotMatch(splashJs,/createObjectURL/);
assert.match(splashJs,/video\.play\(\)/);
assert.match(splashJs,/video\.loop=false/);
assert.match(splashJs,/addEventListener\('ended',markVideoDone/);
assert.match(splashJs,/FALLBACK_DURATION_MS=5200/);
assert.match(splashJs,/boardReady&&videoDone/);
assert.match(splashJs,/MutationObserver/);
assert.match(splashJs,/Complete\|Analysing\|Refresh failed/);
assert.match(splashJs,/15000/);
assert.ok(existsSync(splashAsset),'Zeus loading poster must exist');
assert.ok(videoBuffer.length>20000,'Zeus loading MP4 must contain real video bytes');
assert.equal(videoBuffer.toString('ascii',4,8),'ftyp','Zeus loading asset must be an MP4');
assert.match(serverSource,/zeus-thunder\.part01/);
assert.match(serverSource,/Buffer\.from\(\[p1,p2,p3,p4,p5\]\.join\(''\),'base64'\)/);
assert.match(serverSource,/function serveSplashVideo/);
assert.match(serverSource,/\/media\/zeus-thunder\.mp4/);
assert.match(serverSource,/content-type':'video\/mp4/);
assert.match(serverSource,/accept-ranges':'bytes/);
assert.match(serverSource,/content-range/);
assert.match(serverSource,/media-src 'self'/);
assert.match(ratedHtml,/Highly Rated/);
assert.match(ratedHtml,/id="ratedGrid"/);
assert.match(ratedJs,/analysis\?\.banker/);
assert.match(ratedJs,/TOP 4 BANKER/);
assert.match(ratedJs,/HIGHLY RATED/);
assert.match(ratedJs,/View exact 5 \+ 5 maths/);
assert.match(ratedCss,/\.rated-card\.top-four/);
assert.match(ratedLink,/More Highly Rated Picks/);
assert.match(runtimeConfig,/\/media\/team\/\$\{id\}\.png/);
assert.match(serverSource,/media\.api-sports\.io\/football\/teams/);
assert.match(serverSource,/serveTeamCrest/);
assert.match(serverSource,/image\/jpeg/);
assert.match(serverSource,/max-age=604800, immutable/);

console.log('Golden Banker v4.3 engine + compact UI + crest proxy + highly rated page + full-duration contained Zeus splash tests passed');